#' finalRF
#'
#' This function carries out the final master regulator (MR) analysis using the
#' workspace image file from the random forest cross-validation analysis and
#' compares phenotype prediction based on the final MR random forest model to
#' the actual phenotypes in both the training and test sets.
#'
#' @param rfcv_workspace .RData workspace image file containing all the
#' environment variables from the random forest cross-validation analysis with
#' the rfCrossVal function.
#' @param phenotype string indicating the column name labeling the phenotype of
#' interest.
#' @param mr_count numeric indicating how many representative master regulators
#' should be inferred, which is suggested by the random forest cross-validation
#' plot. Defaults to 100.
#' @param prefix string indicating a prefix to be added to all output file
#' names.
#'
#' @return Writes five output files:
#' \enumerate{
#'   \item  A log file recording the standard outputs generated by the function.
#'   \item  A pdf file for the importance plot of the final MR random forest
#'   model that indicates the relative importance of each inferred MR.
#'   \item  A text file with the summary statistics for phenotype prediction
#'   accuracy based on the final MR random forest model in the training and
#'   test sets. For binary phenotypes, these results are from
#'   caret::confusionMatrix, while for continuous phenotypes they are from
#'   stats:lm linear models.
#'   \item  A text file listing the inferred representative phenotypic MRs.
#'   \item  An .RData workspace image file containing all environment variables
#'   from this analysis. This may be useful if one wants to validate the final
#'   MR random forest model in an independent dataset by again comparing actual
#'   phenotype values to those predicted with the MR random forest model.
#' }
#' @export
#'
#' @examples
#' \dontrun{
#' finalRF("Toy_data_rfcv_workspace.RData","Sim_pheno",100,"Toy_data")
#' }
finalRF <- function(rfcv_workspace,phenotype,mr_count=100,prefix){

  # Send standard output to a log file.
  sink(paste(prefix,"_final_rf_MR_std_out.log",sep = ""),type = "output",split = T)

  # Read in workspace
  print("Reading in workspace from random forest cross-validation analysis")
  load(rfcv_workspace)

  # Train a random forest with the top phenotype-associated regulators to pick the top regulators (by importance type 1)
  # as representative phenotypic MRs. The number of desired MRs should have been determined based on the results of the
  # cross-validation random forest analysis in the previous step, and is fed into this analysis as the 3rd argument.
  print(paste("Identifying",mr_count,"representative", phenotype,"master regulators (MRs)"))
  suppressWarnings(RNGkind(sample.kind = "Rounding")) # This is now necessary after R v3.6.0 for consistent results with pre-3.6.0 scripts because the default sampler changed.
  set.seed(135)
  if(bin_pheno){ # If phenotype is binary...
    init_rndFor=randomForest::randomForest(x=t(train_zvip),y=as.factor(train_phenos),ntree = 1000,keep.forest = T,importance = T)
  } else{ # If phenotype is continuous...
    init_rndFor=randomForest::randomForest(x=t(train_zvip),y=train_phenos,ntree = 1000,keep.forest = T,importance = T)
  }
  init_import=randomForest::importance(init_rndFor,type = 1,scale = F)
  init_import=init_import[order(init_import,decreasing = T),,drop=F]
  mrs=rownames(init_import)[1:mr_count]
  train_mrs=train_zvip[mrs,]
  test_mrs=test_zvip[mrs,]

  # Train the final random forest model using only the representative MRs just identified above.
  print("Training final random forest model with only the representative MRs")
  set.seed(314)
  if(bin_pheno){ # If phenotype is binary...
    final_rndFor=randomForest::randomForest(x=t(train_mrs),y=as.factor(train_phenos),xtest = t(test_mrs),ytest = as.factor(test_phenos),
                              ntree = 1000,keep.forest = T,importance = T)
  } else{ # If phenotype is continuous...
    final_rndFor=randomForest::randomForest(x=t(train_mrs),y=train_phenos,xtest = t(test_mrs),ytest = test_phenos,
                              ntree = 1000,keep.forest = T,importance = T)
  }

  # Output MR importance plot from final random forest model
  importancePlot(final_rndFor,phenotype,mr_count,prefix)

  # Check linear models or confusion matrix statistics for phenotype prediction accuracy
  print(paste("Testing linear models associating final MR random forest-predicted",phenotype,"to actual",phenotype,"in both the training and test sets"))
  if(bin_pheno){ # If phenotype is binary...
    sink(paste(prefix,phenotype,"actual_vs_predicted_statistics.txt",sep = "_"),append = F,split = T)
    cat(paste("Training set","\n",sep = ""))
    print(caret::confusionMatrix(final_rndFor$predicted,as.factor(train_phenos)))
    cat(paste("\n","Test set","\n",sep = ""))
    print(caret::confusionMatrix(final_rndFor$test$predicted,as.factor(test_phenos)))
    sink()
  } else{ # If phenotype is continuous...
    train_lm=stats::lm(train_phenos~final_rndFor$predicted)
    test_lm=stats::lm(test_phenos~final_rndFor$test$predicted)
    sink(paste(prefix,phenotype,"actual_vs_predicted_linear_models.txt",sep = "_"),append = F,split = T)
    cat(paste("Training set linear model for actual~predicted",phenotype,"\n"))
    print(summary(train_lm)$coefficients)
    cat(paste("\nadjusted r-squared =",summary(train_lm)$adj.r.squared),"\n")
    cat(paste("\n\nTest set linear model for actual~predicted",phenotype,"\n"))
    print(summary(test_lm)$coefficients)
    cat(paste("\nadjusted r-squared =",summary(test_lm)$adj.r.squared),"\n")
    sink()
  }

  # Output the representative phenotypic MR list and update the workspace in case the final
  # random forest model is needed for any further validation against independent data sets.
  utils::write.table(mrs, file = paste(prefix,"representative",phenotype,"MRs_list.txt",sep = "_"),quote = F,col.names = F,row.names = F)
  save(list=ls(all.names=T),file=paste(prefix,"_final_MR_random_forest_workspace.RData",sep = ""),envir=environment())

  print("Master regulator analysis is complete!")

}
