#' importancePlot
#'
#' This function writes a pdf file of the importance plot for the final random
#' forest model with the representative phenotypic master regulators.
#'
#' @param rndFor random forest model object generated by the randomForest
#' function from the randomForest package.
#' @param phenotype string indicating the column name of the phenotype of
#' interest.
#' @param mr_count numeric indicating how many representative master regulators
#' are being inferred by this analysis.
#' @param prefix string indicating a prefix to be added to the output file
#' name.
#'
#' @return Writes the importance plot from the final random forest model with
#' the representative phenotypic master regulators to a pdf file.
#' @export
#'
#' @examples
#' \dontrun{
#' importancePlot(final_rndFor,"Sim_pheno",100,"Toy_data")
#' }
importancePlot <- function(rndFor,phenotype,mr_count,prefix){

  grDevices::pdf(file=paste(prefix,phenotype,"MRs_importance_plot.pdf",sep = "_"),width = 6,height = 10)
  randomForest::varImpPlot(rndFor,type=1,scale = F,n.var = mr_count,cex = 0.5,main=paste("Final random forest model representative",phenotype,"MRs"))
  grDevices::dev.off()

}
