#' prepActExp
#'
#' This is the wrapper function that infers regulator activities with the VIPER
#' package, upper quantile normalizes and inverse normal transforms the
#' expression data, and ensures the covariables, activity and expression data
#' are properly formatted for downstream master regulator and eQTL/aQTL
#' analyses.
#'
#' @param gene_exp string for the file name of the expression data file (should
#' be appropriately normalized and pre-filtered for expression).
#' @param covariables string for the file name of the covariables data file.
#' @param network string for the file name of an ARACNe network file. IMPORTANT:
#'  this file cannot have a header!!!
#' @param prefix string indicating a prefix to be added to all output file
#' names.
#'
#' @return Writes six output files:
#' \enumerate{
#'   \item  A log file recording the standard outputs generated by the function.
#'   \item  A tab-delimited file for the interactome/regulon generated by the
#'   aracne2regulon() function from the input ARACNe network and expression
#'   data.
#'   \item  A png image file of a density plot for all regulators' matched
#'   activities and expression values Pearson correlations.
#'   \item  A tab-delimited file containing the quantile normalized and inverse
#'   normal transformed expression values for all input genes.
#'   \item  A tab-delimited file containing the quantile normalized and inverse
#'   normal transformed expression values for only expression regulator genes
#'   for which activities were successfully inferred.
#'   \item  A tab-delimited file containing the activities inferred for
#'   expression regulator genes by VIPER.
#' }
#' @export
#'
#' @examples
#' \dontrun{
#' prepActExp(
#' "GEUVADIS_filtered_samples_expressed_genes_logRPKMs_with_symbols.txt",
#' "GEUVADIS_filtered_samples_select_covars.txt",
#' "GEUVADIS_100boots_ARACNe_network_no_header.txt",
#' "Toy_data")
#' }
prepActExp <- function(gene_exp,covariables,network,prefix){

  # Send standard output to a log file.
  sink(paste(prefix,"_VIPER_and_expression_normalization_std_out.log",sep = ""),type = "output",split = T)

  # Change the sample.kind = "Rounding" with RNGkind to ensure reproducibility of results generated with
  # scripts prior to R v3.6.0 that use RNG seeds. The default since v3.6.0 is "Mersenne-Twister".
  suppressWarnings(RNGkind(sample.kind = "Rounding"))

  # Read in the expression values used to infer the ARACNe networks, and the covars file that has the samples
  # in the final order for the eQTL and aQTL analyses
  print("Reading in data sets")
  genes=utils::read.table(gene_exp,sep = "\t",header = T, row.names = 1)
  genes_set=Biobase::ExpressionSet(assayData=as.matrix(genes))
  covars=as.data.frame(t(utils::read.table(covariables,sep="\t",header = T,row.names = 1)))

  # Scale (i.e. Z-transform) genes in the full log2(TPM) dataset.
  print("Z-scaling expression data")
  z_set=zscale.genes(genes,exprSet = T)

  # Convert the ARACNe network to interactome that includes mode of action (MoA) based on both the network and expression data
  print("Generating interactome from ARACNe network and expression data")
  regulon=viper::aracne2regulon(network,genes_set,format="3col") # NOTE: The aracne network file cannot have a header!!!
  regTable=write.regulon3(regulon,file=paste(prefix,"_interactome.txt",sep=""))

  reg_count=sum(!duplicated(regTable$Regulator))
  print(paste(reg_count,"distinct regulators in the interactome",sep = " "))

  # Run VIPER to infer activities of regulators using the inferred interactome.
  vip=viper::viper(z_set,regulon)
  vip_results=Biobase::exprs(vip)  # exprs() extracts the results matrix from the ExpressionSet object that is generated

  # Filter viper activities and expression data to the same samples in the same order as in covars
  filt_exp=genes[,stats::na.omit(match(rownames(covars),colnames(genes)))]
  filt_vip=as.data.frame(vip_results[,stats::na.omit(match(rownames(covars),colnames(vip_results)))])

  # Also, filter filt_exp for regulators with inferred activities in filt_vip
  filt_regs=genes[stats::na.omit(match(rownames(vip_results),rownames(genes))),stats::na.omit(match(rownames(covars),colnames(genes)))]

  # Check to see how well correlated the activities are to their respective expression values.
  print("Checking regulator expression-activity correlations")
  corDensPlot(filt_regs,filt_vip,prefix)

  # Quantile normalize all expressed genes for final sample set
  print("Quantile normalizing and inverse normal transforming expression data for downstream eQTL analyses")
  qn_exp=as.data.frame(preprocessCore::normalize.quantiles(as.matrix(filt_exp)))
  rownames(qn_exp)=rownames(filt_exp)
  colnames(qn_exp)=colnames(filt_exp)

  # Inverse normal transform the quantile normalized filt_exp.
  int_exp=invNormTrans(qn_exp)

  # Filter the int_exp for regulators with inferred activities.
  filt_int_exp=int_exp[stats::na.omit(match(rownames(vip_results),rownames(int_exp))),]

  # Write the filtered, normalized and transformed data to file
  print("Writing output data to file")
  utils::write.table(cbind("Gene_name"=rownames(filt_int_exp),filt_int_exp),
              paste(prefix,"_regulators_QNorm_INT_expression.txt",sep=""),
              sep="\t",quote = F,row.names = F)
  utils::write.table(cbind("Gene_name"=rownames(int_exp),int_exp),
              paste(prefix,"_expressed_genes_QNorm_INT_expression.txt",sep=""),
              sep="\t",quote = F,row.names = F)
  utils::write.table(cbind("Gene_name"=rownames(filt_vip),filt_vip),
              paste(prefix,"_regulators_activities.txt",sep=""),
              sep="\t",quote = F,row.names = F)

  closeAllConnections()

}
